import logging
import os
import time
import uuid
from PIL import Image, ImageDraw, ImageFont
from typing import Optional
from app.core.config import settings

logger = logging.getLogger(__name__)


class ImageGenerationService:
    """
    Mock Image Generation Service Interface.

    Simulates an AI image generation engine (FLUX / ComfyUI / Stable Diffusion):
    - Accepts a detailed prompt and optional reference image.
    - Waits for 5 seconds simulating heavy AI image synthesis.
    - Synthesizes a realistic product lifestyle visual placeholder PNG image.
    - Returns relative web URL path (e.g. '/uploads/generated/lifestyle_123.png').

    ISOLATION & MODULARITY:
    This service is completely isolated. To replace this mock service with real ComfyUI / FLUX API
    in future assignments, ONLY update this single file without modifying any API routes or worker tasks.
    """

    def __init__(self):
        self.output_dir = os.path.join(settings.UPLOAD_DIR, "generated")
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_image(self, prompt: str, reference_image: Optional[str] = None) -> str:
        """
        Primary interface required for Assignment 1.

        Args:
            prompt: Detailed text-to-image prompt generated by Gemini.
            reference_image: Optional reference product image path.

        Returns:
            str: Relative URL path to the generated image.
        """
        logger.info(f"[ImageGenerationService] Received prompt ({len(prompt)} chars). Simulating AI image generation for 5 seconds...")

        # 1. Simulate 5 second processing delay
        time.sleep(5)

        # 2. Render realistic 1024x1024 product lifestyle image graphic
        width, height = 1024, 1024
        filename = f"lifestyle_{uuid.uuid4().hex[:12]}.png"
        file_path = os.path.join(self.output_dir, filename)

        image = Image.new("RGB", (width, height), (15, 23, 42))  # Dark slate studio canvas
        draw = ImageDraw.Draw(image)

        # Draw decorative studio gradient accents
        draw.rectangle([0, 0, width, height], fill=(15, 23, 42))
        draw.ellipse([600, -100, 1100, 400], fill=(99, 102, 241))   # Indigo accent light
        draw.ellipse([-100, 600, 400, 1100], fill=(14, 165, 233))   # Sky blue soft glow

        # Inner lifestyle photo frame panel
        draw.rounded_rectangle([60, 60, 964, 964], radius=28, fill=(30, 41, 59), outline=(99, 102, 241), width=3)

        try:
            font_title = ImageFont.truetype("arial.ttf", 34)
            font_sub = ImageFont.truetype("arial.ttf", 20)
            font_small = ImageFont.truetype("arial.ttf", 14)
        except Exception:
            font_title = ImageFont.load_default()
            font_sub = ImageFont.load_default()
            font_small = ImageFont.load_default()

        # Text overlays
        draw.text((100, 110), "AI GENERATED PRODUCT LIFESTYLE IMAGE", fill=(129, 140, 248), font=font_title)
        draw.text((100, 160), "Render Engine: Mock FLUX.1 / ComfyUI Pipeline (5s Synthesis)", fill=(148, 163, 184), font=font_sub)

        # Prompt Box Display
        draw.rounded_rectangle([100, 220, 924, 860], radius=16, fill=(15, 23, 42), outline=(51, 65, 85), width=2)
        draw.text((130, 250), "INPUT PROMPT PASSED TO GENERATION ENGINE:", fill=(99, 102, 241), font=font_sub)

        wrapped_prompt = self._wrap_text(prompt, max_chars=58)
        draw.text((130, 290), wrapped_prompt, fill=(226, 232, 240), font=font_small, spacing=8)

        draw.text((100, 890), "ComfyUI Integration Ready • Replace image_generation_service.py to connect real engine", fill=(100, 116, 139), font=font_small)

        # Save to disk
        image.save(file_path, "PNG", quality=95)

        web_url = f"/uploads/generated/{filename}"
        logger.info(f"[ImageGenerationService] Generated image successfully saved: {web_url}")
        return web_url

    def generate_image_from_prompt(self, job_id: int, prompt: str) -> str:
        """Backwards compatibility alias method."""
        return self.generate_image(prompt=prompt)

    def _wrap_text(self, text: str, max_chars: int) -> str:
        words = text.split()
        lines = []
        current_line = []
        current_len = 0

        for word in words:
            if current_len + len(word) + 1 > max_chars:
                lines.append(" ".join(current_line))
                current_line = [word]
                current_len = len(word)
            else:
                current_line.append(word)
                current_len += len(word) + 1

        if current_line:
            lines.append(" ".join(current_line))

        return "\n".join(lines[:20])


image_generation_service = ImageGenerationService()
